title: Keshav Singh
logo: /assests/2.jpeg
description: As a MSc Management student specializing in Information Science and Engineering, I am available to start working from September, seeking roles in Data Science, Data Engineering, or Business Intelligence. Proficient in Python, SQL, AWS, ETL, and machine learning, including NLP, LSTM, and reinforcement learning, developing impactful deep learning solutions with TensorFlow and Keras. My expertise in data visualization further enhances decision-making and business insights.
theme: jekyll-theme-minimal
